config/routes.rb
Rails.application.routes.draw do

  resources :parties
  resources :items
  resources :orders
  resources :admins
  resources :employees

  get '/login' => 'employees#log_in'
  get '/menu' => 'admins#menu'
  get '/cashout' => 'orders#cashout'
  post "/session" => 'session#create'
  delete "/session" => 'session#destroy'

  put 'parties/:id/pay' => 'parties#pay', as: :pay

  put '/order_complete/:id' => 'order#complete', as: "order_complete"
  put '/party_euro/:id' => 'parties#euro', as: "party_euro"
  put '/party_american/:id' => 'parties#american', as: "party_american"

  root 'welcome#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password
end

app/models/employee.rb
class Employee < ActiveRecord::Base
    has_secure_password
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :orders
  has_many :parties, through: :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :party
  belongs_to :item


  def subtotal
    item.price * quantity
  end


end

app/models/party.rb
class Party < ActiveRecord::Base
  has_many :orders
  has_many :items, through: :orders


  # def total
  #   total = 0
  #   newtotal = order.subtotal
  #   newtotal.each do |i|
  #     total += newtotal
  #   end
  # end

  def total
   total = 0
   self.orders.each do |order|
     total += order.subtotal
   end
   return total
  end


end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
before_filter :confirm_logged_in, :only => [:show]
    def index
    end

    def new
      @admin = Admin.new
    end

    def create
      admin = Admin.create(admin_params)
      if admin.save
        session[:admin_id] = admin.id
        redirect_to '/admins/log_in'
      else
        flash[:error] = admin.errors.full_messages
        redirect_to new_admin_path
      end
    end

    def log_in
    end

    def menu
      @items = Item.all
    end

    def show
      @items = Item.all
    end

  private
    def admin_params
      parameters = params.require(:admin).permit(:username, :password, :password_confirmation)
    end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
before_filter :confirm_logged_in, :only => [:show]
  def index
  end

  def new
    @employee = Employee.new
  end

  def create
    employee = Employee.create(employee_params)
    if employee.save
      session[:employee_id] = employee.id
      redirect_to '/employees'
    else
      flash[:error] = employee.errors.full_messages
      redirect_to new_employee_path
    end
  end

  def log_in
  end

  def menu
    @items = Item.all
  end

  def show
    @items = Item.all
  end

private
  def employee_params
    parameters = params.require(:employee).permit(:username, :password, :password_confirmation, :firstname, :lastname, :address1, :address2, :city, :state, :zip, :phone_number, :dob, :job_title, :is_admin)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
before_filter :confirm_logged_in, :only => [:show]
  def index
    @items = Item.all
  end

  def create
    items = Item.create(item_params)
    if items.save
      redirect_to items_path
    else
    flash[:error] = items.errors.full_messages
    redirect_to new_items_path
    end
  end

  def new
    @items = Item.new
  end

  def update
    items = Item.find(params[:id])
    if items.update(item_params)
      redirect_to items_path
    else
      flash[:error] = items.errors.full_messages
      redirect_to edit_items_path(items.id)
    end
  end

  def edit
    @items = Item.find(params[:id])
  end

  def show
    @items = Item.find(params[:id])
  end

  def destroy
    Item.delete(params[:id])
    redirect_to 'admins/menu'
  end

private
  def item_params
    params.require(:item).permit(:name, :price, :description)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
before_filter :confirm_logged_in, :only => [:show]
    def index
      @order = Order.new
      @orders = Order.order('created_at ASC').all
    end

    def cashout
      @order = Order.new
    end

    def create
      Order.create(order_params)
      redirect_to orders_path
    end

    def new
      @order = Order.new
    end

    def show
      @order = Order.find(params[:id])
    end

   def update
      order = Order.find(params[:id])
      order.update(order_params)
      redirect_to "/orders"
    end

    def edit
      @orders = Order.find(params[:id])
    end

    def destroy
      Order.delete(params[:id])
      redirect_to orders_path
    end


    private

    def order_params
      params.require(:order).permit(:party_id, :item_id, :quantity)
    end

end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController

  def index
    @parties = Party.all
  end

  def create
    party = Party.create(party_params)
    redirect_to '/parties'
  end

  def new
    @party = Party.new
  end

  def show
    @party = Party.find(params[:id])
  end

  def update
    party = Party.find(party_params)
  end

  def destroy
    Party.delete(params[:id])
    redirect_to parties_path
  end

  def pay
  party = Party.find(params[:id])
  party.update_attribute(:is_paid, "true")
  end

  def euro
  party = Party.find(params[:id])
  party.update({euro: true})
  redirect_to "/parties/#{party.id}"
  end

  def american
  party = Party.find(params[:id])
  party.update({euro: false})
  redirect_to "/parties/#{party.id}"
  end

  private
  def party_params
    parameters = params.require(:party).permit(:guest_total, :top_number)
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end
  def create
    employee = Employee.find_by_username(params[:username])
    if employee && employee.authenticate(params[:password])
      session[:employee_id] = employee.id
      redirect_to employees_path
    else
      redirect_to log_in_path
    end
  end

  def destroy
    session[:employee_id] = nil
    redirect_to log_in_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/edit.html.erb
<%= stylesheet_link_tag    'admins', media: 'all', 'data-turbolinks-track' => true %>
<h2>Update Admin</h2>

<%= form_for @admin do |f| %>
<%= f.text_field :username %>
<%=f.text_field :password %>
<%= f.submit :class => "button-primary" %>
<% end %>

app/views/admins/index.html.erb
<%= stylesheet_link_tag    'admins', media: 'all', 'data-turbolinks-track' => true %>

<h4>Admin Page</h4>
<%= button_to "New Admin", "/admins/new", class: "button"%>
<%= button_to "New Employee", "/admins/new", class: "button"%>
<%= button_to "Update Menu", "/admins/menu", class: "button"%>

app/views/admins/log_in.html.erb
<%= stylesheet_link_tag    'admins', media: 'all', 'data-turbolinks-track' => true %>
<h4>Login</h4>
<%=form_tag session_path do %>
  <p>Username</p>
  <%= text_field_tag :username %>
  <p>Password</p>
  <%= password_field_tag :password %>
  <%= submit_tag "Log In", class: "button-primary"%>
<%end%>

app/views/admins/menu.html.erb
<%= stylesheet_link_tag    'admins', media: 'all', 'data-turbolinks-track' => true %>
<h4>Update Menu</h4>

<% @items.in_groups_of(3, false).each do |group| %>
<div class="row ">
 <% group.each do |item| %>
 <div class="large-4 columns color">
<strong><%= item.name %></strong><br>
<%= item.description %><br>
<%= item.price %><br>
<%= button_to "Remove", item_path(item), method: :delete, class: "button-primary"%>
<%= button_to "Edit", edit_item_path(item), method: :get, class: "button-primary" %>
</div>
<% end %>
</div>
<% end %>

app/views/admins/new.html.erb
<%= stylesheet_link_tag   'admins', media: 'all', 'data-turbolinks-track' => true %>
<h4>New Admin</h4>
<%= form_for @admin do |f| %>
  <div class="row">
    <div class="four columns">
      <%= f.text_field :username %>
    </div>
  <div class="four columns">
    <%=f.text_field :password %>
  </div>
  <div class="four columns">
    <%= f.submit :class => "button submit" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Serve.r" %></title>
    <link href='https://fonts.googleapis.com/css?family=Dancing+Script:400,700' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><a class="siteTitle" href="/">Serve.r</a></h1>
        </li>
         <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <!-- Left Nav Section -->
        <ul class="left">
          <li class="has-dropdown">
            <a href="#">Orders</a>
            <ul class="dropdown">
              <li><a href="/orders">All Orders</a></li>
              <li><a href="/orders/new">New Order</a></li>
            </ul>
          </li>
          <li class="has-dropdown">
            <a href="#">Parties</a>
            <ul class="dropdown">
              <li><a href="/parties">All Parties</a></li>
              <li><a href="/parties">New Party</a></li>
            </ul>
          </li>
          <li class="has-dropdown">
            <a href="#">Employees</a>
            <ul class="dropdown">
              <li><a href="/log_in">Admin Login</a></li>
              <li><a href="/log_in">Employee Login</a></li>
            </ul>
          </li>
          <li><a href="/items">Menu</a></li>
        </ul>
      </section>
    </nav>

    <%= yield %>

  </body>
</html>