config/routes.rb
Rails.application.routes.draw do

  resources :parties
  resources :items
  resources :orders
  resources :admins
  resources :employees

  get '/login' => 'employees#log_in'
  get '/menu' => 'admins#menu'
  get '/cashout' => 'orders#cashout'
  post "/session" => 'session#create'
  delete "/session" => 'session#destroy'

  put 'parties/:id/pay' => 'parties#pay', as: :pay

  put '/order_complete/:id' => 'order#complete', as: "order_complete"
  put '/party_euro/:id' => 'parties#euro', as: "party_euro"
  put '/party_american/:id' => 'parties#american', as: "party_american"

  root 'welcome#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password
end

app/models/employee.rb
class Employee < ActiveRecord::Base
    has_secure_password
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :orders
  has_many :parties, through: :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :party
  belongs_to :item


  def subtotal
    item.price * quantity
  end


end

app/models/party.rb
class Party < ActiveRecord::Base
  has_many :orders
  has_many :items, through: :orders


  # def total
  #   total = 0
  #   newtotal = order.subtotal
  #   newtotal.each do |i|
  #     total += newtotal
  #   end
  # end

  def total
   total = 0
   self.orders.each do |order|
     total += order.subtotal
   end
   return total
  end


end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
before_filter :confirm_logged_in, :only => [:show]
    def index
    end

    def new
      @admin = Admin.new
    end

    def create
      admin = Admin.create(admin_params)
      if admin.save
        session[:admin_id] = admin.id
        redirect_to '/admins/log_in'
      else
        flash[:error] = admin.errors.full_messages
        redirect_to new_admin_path
      end
    end

    def log_in
    end

    def menu
      @items = Item.all
    end

    def show
      @items = Item.all
    end

  private
    def admin_params
      parameters = params.require(:admin).permit(:username, :password, :password_confirmation)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

protected

def confirm_logged_in
  unless session[:id]
      flash[:notice] = "Please log in"
      redirect_to :root
      return false
  else
      return true
  end
end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
before_filter :confirm_logged_in, :only => [:show]
  def index
  end

  def new
    @employee = Employee.new
  end

  def create
    employee = Employee.create(employee_params)
    if employee.save
      session[:employee_id] = employee.id
      redirect_to '/employees'
    else
      flash[:error] = employee.errors.full_messages
      redirect_to new_employee_path
    end
  end

  def log_in
  end

  def menu
    @items = Item.all
  end

  def show
    @items = Item.all
  end

private
  def employee_params
    parameters = params.require(:employee).permit(:username, :password, :password_confirmation, :firstname, :lastname, :address1, :address2, :city, :state, :zip, :phone_number, :dob, :job_title, :is_admin)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
before_filter :confirm_logged_in, :only => [:show]
  def index
    @items = Item.all
  end

  def create
    items = Item.create(item_params)
    if items.save
      redirect_to items_path
    else
    flash[:error] = items.errors.full_messages
    redirect_to new_items_path
    end
  end

  def new
    @items = Item.new
  end

  def update
    items = Item.find(params[:id])
    if items.update(item_params)
      redirect_to items_path
    else
      flash[:error] = items.errors.full_messages
      redirect_to edit_items_path(items.id)
    end
  end

  def edit
    @items = Item.find(params[:id])
  end

  def show
    @items = Item.find(params[:id])
  end

  def destroy
    Item.delete(params[:id])
    redirect_to 'admins/menu'
  end

private
  def item_params
    params.require(:item).permit(:name, :price, :description)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
before_filter :confirm_logged_in, :only => [:show]
    def index
      @order = Order.new
      @orders = Order.order('created_at ASC').all
    end

    def cashout
      @order = Order.new
    end

    def create
      Order.create(order_params)
      redirect_to orders_path
    end

    def new
      @order = Order.new
    end

    def show
      @order = Order.find(params[:id])
    end

   def update
      order = Order.find(params[:id])
      order.update(order_params)
      redirect_to "/orders"
    end

    def edit
      @orders = Order.find(params[:id])
    end

    def destroy
      Order.delete(params[:id])
      redirect_to orders_path
    end


    private

    def order_params
      params.require(:order).permit(:party_id, :item_id, :quantity)
    end

end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController

  def index
    @parties = Party.all
  end

  def create
    party = Party.create(party_params)
    redirect_to '/parties'
  end

  def new
    @party = Party.new
  end

  def show
    @party = Party.find(params[:id])
  end

  def update
    party = Party.find(party_params)
  end

  def destroy
    Party.delete(params[:id])
    redirect_to parties_path
  end

  def pay
  party = Party.find(params[:id])
  party.update_attribute(:is_paid, "true")
  end

  def euro
  party = Party.find(params[:id])
  party.update({euro: true})
  redirect_to "/parties/#{party.id}"
  end

  def american
  party = Party.find(params[:id])
  party.update({euro: false})
  redirect_to "/parties/#{party.id}"
  end

  private
  def party_params
    parameters = params.require(:party).permit(:guest_total, :top_number)
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end
  def create
    employee = Employee.find_by_username(params[:username])
    if employee && employee.authenticate(params[:password])
      session[:employee_id] = employee.id
      redirect_to employees_path
    else
      redirect_to log_in_path
    end
  end

  def destroy
    session[:employee_id] = nil
    redirect_to log_in_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/employees/index.html.erb
<h4>Employees</h4>

app/views/employees/log_in.html.erb
<h4>login</h4>

app/views/employees/new.html.erb
<h4>New Employee</h4>
<%= form_for @employee do |f| %>
<div class="row">
    <div class="large-6 columns">
      <label>Username
      <%= f.text_field :username %>
      </label>
    </div>
    <div class="large-6 columns">
    <label>Password
    <%=f.text_field :password %>
    </label>
  </div>
</div>
<div class="row">
  <div class="large-6 columns">
    <label>First Name
    <%=f.text_field :firstname %>
    </label>
  </div>
  <div class="large-6 columns">
    <label>Last Name
    <%=f.text_field :lastname %>
    </label>
  </div>
</div>
<div class="row">
  <div class="large-6 columns">
  <label>Address Line 1
  <%=f.text_field :address1 %>
  </label>
  </div>
  <div class="large-6 columns">
    <label>Address Line 2
    <%=f.text_field :address2 %>
    </label>
  </div>
</div>
<div class="row">
    <div class="large-4 columns">
      <label>City
      <%=f.text_field :city %>
      </label>
    </div>
    <div class="large-4 columns">
      <label>State
      <%=f.text_field :state %>
      </label>
    </div>
    <div class="large-4 columns">
      <label>Zip
      <%=f.text_field :zip %>
      </label>
    </div>
</div>
<div class="row">
  <div class="large-3 columns">
    <label>Phone Number
    <%=f.text_field :phone_number %>
    </label>
  </div>
  <div class="large-3 columns">
    <label>Date of Birth
    <%=f.text_field :dob %>
    </label>
  </div>
  <div class="large-3 columns">
    <label>Job Title
    <%=f.text_field :job_title %>
    </label>
  </div>
  <div class="large-3 columns">
  <label>Administrator Access
  <%=f.text_field :is_admin %>
  </label>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <%= f.submit :class => "button submit" %>
  </div>
</div>
<% end %>

app/views/items/edit.html.erb
<h2>Update Order</h2>

<%= form_for @items do |f| %>
  <p> Name <%= f.text_field :name %> </p>
  <p> Description <%= f.text_field :description %> </p>
  <p> Price <%= f.text_field :price %> </p>
  <%= f.submit %>
<% end%>

app/views/items/index.html.erb
<%= stylesheet_link_tag    'items', media: 'all', 'data-turbolinks-track' => true %>
<h4>Menu</h4>
  <% @items.in_groups_of(3, false).each do |group| %>
  <div class="row">
   <% group.each do |item| %>
   <div class="large-4 columns items">
  <strong><%= item.name %></strong><br>
  <%= item.description %><br>
  <%= item.price %><br>
  </div>
  <% end %>
  </div>
  <% end %>

app/views/items/new.html.erb
<%= stylesheet_link_tag    'items', media: 'all', 'data-turbolinks-track' => true %>
<h4>New Menu Item</h4>
<%= form_for @items do |f| %>
  <div class="row">
    <div class="large-6 columns">
      <label>Name
        <%= f.text_field :name %>
      </label>
    </div>
    <div class="large-6 columns">
      <label> Price <%= f.text_field :price %>
      </label>
    </div>
    <div class="row">
      <div class="large-12 columns">
        <label> Description
          <%= f.text_field :description %>
        </label>
      </div>
    </div>
    <div class="row">
      <%= f.submit %>
    </div>
<% end%>

app/views/orders/edit.html.erb
<h4>Update Order</h4>

<%= form_for @orders do |f| %>
<div class="row">
<div class="four columns">
<%= f.label :name %>
<%= f.collection_select :item_id, Item.all, :id, :name, class: "u-full-width"%>
</div>
<div class="four columns">
<%= f.label :party_id %>
<%= f.collection_select :party_id, Party.all, :id, :id, class: "u-full-width"%>
</div>
<div class="four columns">
<%= f.label :quantity %>
<%= f.text_field :quantity %>
</div>
<div class="four columns">
<%= f.submit :class => "button submit" %>
</div>
<% end %>

app/views/orders/index.html.erb
<%= stylesheet_link_tag    'orders', media: 'all', 'data-turbolinks-track' => true %>
<div class="row">
  <div class="four columns"></div><div class="four columns"><h4>CURRENT ORDERS</h4></div><div class="four columns"></div>
</div>

  <% @orders.in_groups_of(3, false).each do |group| %>
  <div class="row order">
   <% group.each do |order| %>
   <div class="large-4 columns color">
     <span class="white">Item: </span><span class="blue"><%= order.item.name %></span><br>
     <span class="white">Price: </span><span class="blue"><%= order.item.price %></span><br>
     <span class="white">Quantity: </span><span class="blue"><%= order.quantity %></span><br>
     <span class="white">Subtotal: </span><span class="blue"><%= order.subtotal %></span><br>
     <span class="white">Party: </span><span class="blue"><%= order.party_id %></span><br>
     <span class="white">Notes: </span><span class="blue"><%= order.note %></span><br>
   <% if order.created_at.to_time > 15.minutes.ago  %>
   <span class="green"><%= order.created_at.to_time.strftime('%l:%M %p %Z')%></span><br>
   <% elsif order.created_at.to_time < 15.minutes.ago && order.created_at.to_time > 50.minutes.ago %>
   <span class="yellow"><%= order.created_at.to_time.strftime('%l:%M %p %Z')%></span><br>
   <% elsif order.created_at.to_time < 30.minutes.ago %>
   <span class="red"><%= order.created_at.to_time.strftime('%l:%M %p %Z')%></span><br>
   <% end %>
   <div class="row">
   <br>
   <div class="large-6 columns"><%= button_to " Edit ", edit_order_path(order), method: :get, type: "button", class: "button tiny" %></div>
   <div class="large-6 columns"><%= button_to " Remove ", order_path(order), method: :delete, type: "button", class: "alert button tiny" %></div>
   </div>
 </div>
<% end %>
</div>
<% end %>

app/views/orders/new.html.erb
<%= stylesheet_link_tag    'orders', media: 'all', 'data-turbolinks-track' => true %>
<h4 class="white">New Order</h4>
<br>
<%= form_for @order do |f| %>
<div class="row">
<%= f.label :name, class: "white" %>
<%= f.collection_select :item_id, Item.all, :id, :name, class: "twelve columns"%><br>
<%= f.label :party_id, class: "white" %>
<%= f.collection_select :party_id, Party.all, :id, :id, class: "twelve columns"%><br>
<%= f.label :quantity, class:"white" %>
<%= f.text_field :quantity, class: "twelve columns" %><br>
<%= f.label :note, class: "white" %>
<%= f.text_field :note, class: "twelve columns" %><br>
<%= f.submit :class => "button submit" %>
</div>
<% end %>

app/views/parties/index.html.erb
<%= stylesheet_link_tag    'parties', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'parties', 'data-turbolinks-track' => true %>
<h2>Current Parties</h2>


<% @parties.in_groups_of(3, false).each do |group| %>
<div class="row order">
 <% group.each do |party| %>
 <div class="large-4 columns color">
<span class="white">Party No:&nbsp;<%= party.id %></span><br>
<span class="white">Party Name:<%= party.name %></span><br>
<span class="white">Guests:&nbsp;<%= party.guest_total %></span><br>
<span class="white">Table No:&nbsp;<%= party.top_number %></span><br>
<%= link_to "Cash Out", "/parties/#{party.id}", class: "cashout" %>
<%= button_to "Remove", party_path(party), method: :delete, class: "button-primary" %>
    </div>
  <% end %>
</div>
<% end %>



<div id="modal">
  <div class="modal-content">
    <div class="modal-header">
      <h3> MODAL TIME!!! </h3>
      <div id="close-modal"> X </div>
    </div>
    <div class="modal-body">
        <input id="img-url"/>
        <button id="submit-btn"> Submit </button>
      </div>
    </div>
</div>
<button id="open-modal"> Open My Modal </button>

app/views/parties/new.html.erb
<%= stylesheet_link_tag    'parties', media: 'all', 'data-turbolinks-track' => true %>

<h4>Add A New Party</h4>
<br>
<%= form_for @party do |f| %>
<div class="row">
  <div class="twelve columns">
  <%= f.label :name, "Party Name" %>
  <%= f.text_field :name %><br>
</div>
<div class="twelve columns">
  <%= f.label :guest_total, "Number of Guests" %>
  <%= f.text_field :guest_total %><br>
</div>
<div class="twelve columns">
  <%= f.label :top_number, "Table Number" %>
  <%= f.text_field :top_number %><br>
<div>
  <div class="twelve columns">
  <%= f.submit :class => "button submit"%>
</div>
<% end %>

app/views/parties/show.html.erb
<%= stylesheet_link_tag    'parties', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'parties', 'data-turbolinks-track' => true %>

<h4>Bill For Party Number: <%= @party.id %></h4>
<div class="row">
  <div class="two columns bill">
<% @party.orders.each do |order| %>
<% if @party.euro == false %>
    <%= order.quantity %>&nbsp;<%= order.item.name %>&nbsp;&#8212;&nbsp;&#36;<%= order.item.price * order.quantity %><br>
<% elsif @party.euro == true %>
  <%= order.quantity %>&nbsp;<%= order.item.name %>&nbsp;&#8212;&nbsp;&#8364;<%= '%.2f' % (order.item.price / 0.92) %><br>
<% end %>
<% end %>
</div>
</div>
<br>
<% if @party.euro == false %>
<p>Subtotal:<%= '%.2f' % (@party.total) %></p>
<p>Tax: <%= '%.2f' % (@party.total * 0.09) %></p>
<p class="total">TOTAL: <%= '%.2f' % (@party.total + (@party.total * 0.09)) %></p>
<p>Add 15% Tip: <%= '%.2f' % (@party.total + (@party.total * 0.15) + (@party.total * 0.09)) %></p>
<p>Add 20% Tip: <%= '%.2f' % (@party.total + (@party.total * 0.20) + (@party.total * 0.09)) %></p>
<p>Add 25% Tip: <%= '%.2f' % (@party.total + (@party.total * 0.25) + (@party.total * 0.09)) %></p>
<p><%= button_to "Euro", party_euro_path, method: :put, class: "button tiny" %></p>
<% elsif @party.euro == true %>
<p>Subtotal:&nbsp;&#8364;<%= '%.2f' % (@party.total / 0.92) %></p>
<p>Tax:&nbsp;&#8364;<%= '%.2f' % (((@party.total / 0.92) * 0.09)) %></p>
<p class="total">TOTAL:&nbsp;&#8364;<%= '%.2f' % ((@party.total / 0.92) + ((@party.total / 0.92) * 0.09)) %></p>
<p>Add 15% Tip:&nbsp;&#8364;<%= '%.2f' % ((@party.total / 0.92) + ((@party.total / 0.92) * 0.15) + ((@party.total / 0.92) * 0.09)) %></p>
<p>Add 20% Tip:&nbsp;&#8364;<%= '%.2f' % ((@party.total / 0.92) + ((@party.total / 0.92) * 0.20) + ((@party.total / 0.92) * 0.09)) %></p>
<p>Add 25% Tip:&nbsp;&#8364;<%= '%.2f' % ((@party.total / 0.92) + ((@party.total / 0.92)* 0.25) + ((@party.total / 0.92) * 0.09)) %></p>
<p><%= button_to "American", party_american_path, method: :put, class: "button tiny" %></p>
<% end %>

app/views/welcome/index.html.erb
<%= stylesheet_link_tag    'welcome', media: 'all', 'data-turbolinks-track' => true %>
<h4>Employee Login</h4>
<%=form_tag session_path do %>
<div class="row">
  <div class="large-6 columns">
  <label>Username
  <%= text_field_tag :username %>
</label>
</div>
<div class="large-6 columns">
  <label>Password</label>
  <%= password_field_tag :password %>
</label>
</div>
<div class="row">
  <div class="large-12 columns">
  <%= submit_tag "Log In", class: "button submit"%>
  </div>
</div>
<%end%>